// Shared constants used across services and validation
const MAX_IMAGE_UPLOAD_BYTES = 20 * 1024 * 1024;
const PROVIDER_MAX_IMAGE_BYTES = 5 * 1024 * 1024;
const PROVIDER_MIN_IMAGE_EDGE = 150;
const PROVIDER_MAX_IMAGE_EDGE = 4096;
const MIN_IMAGE_UPLOAD_BYTES = 5 * 1024;

module.exports = {
  MAX_IMAGE_UPLOAD_BYTES,
  PROVIDER_MAX_IMAGE_BYTES,
  PROVIDER_MIN_IMAGE_EDGE,
  PROVIDER_MAX_IMAGE_EDGE,
  MIN_IMAGE_UPLOAD_BYTES
};
